print("CS151 Lab ")
print("Jenna")
print("brown hair")
print("brown eyes")
print("short")
print("freckles")
print("green shirt")
print("Caitlin")
print("brown hair")
print("blue eyes")
print("freckles")
print("long hair")
print("grey shirt")
